/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stm32f0xx.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void Init_Clock();
void Init_Pin();

int main() {
	Init_Clock();
	Init_Pin();

	while (1) {
		GPIOA->BSRR  |= (1 << 21);
		for (volatile int i = 0; i < 30000; i++) {
			asm("nop");
		}
		GPIOA->BSRR |= (1 << 5);
		for (volatile int i = 0; i < 30000; i++) {
			asm("nop");
		}
	}
}

void Init_Clock() {
	RCC->CR |= (1 << 0); /* HSI on */
	while (((RCC->CR >> 1) & 1UL) == 0) {

	}

	FLASH->ACR &= ~(7 << 0); /* Zero wait state */

	RCC->CFGR &= ~(1 << 7); /* HCLK not divided */
	RCC->CFGR &= ~(1 << 10); /* PCLK not divided */

	RCC->CFGR &= ~(1 << 3); /* Use HSI */
	RCC->CFGR &= ~(1 << 2);
}

void Init_Pin() {
	RCC->AHBENR |= (1 << 17); /* CLK to PORTA */

	GPIOA->MODER &= ~(1 << 11);
	GPIOA->MODER |= (1 << 10); /* PA5 as generic output */

	GPIOA->ODR &= ~(1 << 5);
}
